// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pizzeria.API.Infrastructure.Database;

#nullable disable

namespace Pizzeria.API.Infrastructure.Database.Migrations
{
    [DbContext(typeof(PizzeriaDbContext))]
    [Migration("20260423202008_AddProductImages")]
    partial class AddProductImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pizzeria.API.Modules.DeliveryPersons.Entities.DeliveryPerson", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Code");

                    b.ToTable("delivery_persons", (string)null);
                });

            modelBuilder.Entity("Pizzeria.API.Modules.Ingredients.Entities.Ingredient", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("images");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("numeric(12, 4)");

                    b.Property<decimal>("Stock")
                        .HasColumnType("numeric(12, 3)");

                    b.Property<string>("Supplier")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Code");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("Pizzeria.API.Modules.Orders.Entities.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AssignedDeliveryPersonCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDeliveryPersonCode");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Pizzeria.API.Modules.Orders.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PizzaId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PizzaId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Pizzeria.API.Modules.Pizzas.Entities.Pizza", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("images");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("pizzas", (string)null);
                });

            modelBuilder.Entity("Pizzeria.API.Modules.Pizzas.Entities.PizzaIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IngredientCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PizzaId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(12, 3)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientCode");

                    b.HasIndex("PizzaId", "IngredientCode")
                        .IsUnique();

                    b.ToTable("pizza_ingredients", (string)null);
                });

            modelBuilder.Entity("Pizzeria.API.Modules.Orders.Entities.Order", b =>
                {
                    b.HasOne("Pizzeria.API.Modules.DeliveryPersons.Entities.DeliveryPerson", null)
                        .WithMany()
                        .HasForeignKey("AssignedDeliveryPersonCode")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Pizzeria.API.Modules.Orders.Entities.OrderItem", b =>
                {
                    b.HasOne("Pizzeria.API.Modules.Orders.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pizzeria.API.Modules.Pizzas.Entities.Pizza", null)
                        .WithMany()
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pizzeria.API.Modules.Pizzas.Entities.PizzaIngredient", b =>
                {
                    b.HasOne("Pizzeria.API.Modules.Ingredients.Entities.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pizzeria.API.Modules.Pizzas.Entities.Pizza", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pizzeria.API.Modules.Orders.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Pizzeria.API.Modules.Pizzas.Entities.Pizza", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
